export enum EventoTipoEnum {
  // Usuarios
  USUARIO_CREADO = 'USUARIO_CREADO',
  USUARIO_ACTUALIZADO = 'USUARIO_ACTUALIZADO',
  USUARIO_ACTIVADO = 'USUARIO_ACTIVADO',
  USUARIO_DESACTIVADO = 'USUARIO_DESACTIVADO',
  ROL_ASIGNADO = 'ROL_ASIGNADO',
  
  // Facultades
  FACULTAD_CREADA = 'FACULTAD_CREADA',
  FACULTAD_ACTUALIZADA = 'FACULTAD_ACTUALIZADA',
  FACULTAD_ELIMINADA = 'FACULTAD_ELIMINADA',
  
  // Carreras
  CARRERA_CREADA = 'CARRERA_CREADA',
  CARRERA_ACTUALIZADA = 'CARRERA_ACTUALIZADA',
  CARRERA_ELIMINADA = 'CARRERA_ELIMINADA',
  
  // Informes y documentos
  INFORME_CREADO = 'INFORME_CREADO',
  INFORME_REVISADO = 'INFORME_REVISADO',
  INFORME_APROBADO = 'INFORME_APROBADO',
  DOCUMENTO_SUBIDO = 'DOCUMENTO_SUBIDO',
  
  // Acreditación
  PROCESO_ACREDITACION_INICIADO = 'PROCESO_ACREDITACION_INICIADO',
  ACREDITACION_ACTUALIZADA = 'ACREDITACION_ACTUALIZADA',
  
  // EUR-ACE
  CRITERIO_EUR_ACE_CREADO = 'CRITERIO_EUR_ACE_CREADO',
  
  // OPP (Objetivos de Programa)
  OBJETIVO_PROGRAMA_CREADO = 'OBJETIVO_PROGRAMA_CREADO',
  
  // Resultados de Aprendizaje
  RESULTADO_APRENDIZAJE_CREADO = 'RESULTADO_APRENDIZAJE_CREADO',
  
  // Autenticación
  LOGIN_EXITOSO = 'LOGIN_EXITOSO',
  LOGIN_FALLIDO = 'LOGIN_FALLIDO',
  LOGOUT = 'LOGOUT',
}