export enum RolEnum {
  ADMINISTRADOR = 'ADMINISTRADOR',
  DGIP = 'DGIP',
  PROFESOR = 'PROFESOR',
  DECANO = 'DECANO',
  SUBDECANO = 'SUBDECANO',
  JEFE_DEPARTAMENTO = 'JEFE_DEPARTAMENTO',
  COORDINADOR = 'COORDINADOR',
  CEI = 'CEI',
}